### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by filmor** [Pyrlang/Term#3]
It would be very useful if this package (as well as pyrlang) could be published to pypi. Sadly, the name `term` is already taken, but publishing to `pyrlang-term` should be fine, I highly doubt that someone would want to do tty operations in an Erlang node.

If you don't have the time to work on this but like the idea, I can prepare a PR :)

**Comment by s2hc-johan** [comment]
Hi,
We do want this and pyrlang to be published to pypi. The idea was to get a web page up and running before releasing it to the wild.

Also it's still verry young, but that shouldn't stop publishing it.

You're more then welcome to help with a PR. Glad to see someone else is using it!
